CREATE TABLE MEMBRES (
  CODE_MEMBRE NUMBER NOT NULL ENABLE, 
	NOM VARCHAR2(30 BYTE), 
	PRENOM VARCHAR2(30 BYTE), 
	ADRESSE VARCHAR2(50 BYTE), 
	STATUS VARCHAR2(10 BYTE), 
	REVENUE_ANNUEL NUMBER(8,2), 
	CONSTRAINT MEMBRES_PK PRIMARY KEY (CODE_MEMBRE));
